version: '3'

services:
    reverseproxy:
        build: ./reverseproxy
        image: reverseproxy
        ports:
            - 80:80
            - 8081:8081
        restart: always

    tmilner:
        depends_on:
            - reverseproxy
        build: .
        image: tmilner
        restart: always

    monzo-customisation:
        depends_on:
            - reverseproxy
        image: monzo-customisation
        restart: always